{% set name = "flytekitplugins-athena" %}
{% set version = "1.2.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/flytekitplugins-athena-{{ version }}.tar.gz
  sha256: 9bd7de6856d88472b2566a06227d8420b976f244ed442a2f677f6b2d76936c88

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.7
  run:
    - python >=3.7
    - flytekit >=1.0.0b3,<1.2.0

test:
  imports:
    - flytekitplugins.athena
  # commands:
  #   - pip check
  requires:
    - pip

about:
  home: https://pypi.org/project/flytekitplugins-athena/
  summary: This package holds the Athena plugins for flytekit
  license: Apache-2.0
  license_file:
    - LICENSE
    - NOTICE
  description: |
    Athena plugin for Flytekit: `{{ name }}`

    PyPI: [https://pypi.org/project/flytekitplugins-athena/](https://pypi.org/project/flytekitplugins-athena/)

  doc_url: https://github.com/flyteorg/flytekit/tree/master/plugins
  dev_url: https://github.com/flyteorg/flytekit/tree/master/plugins/flytekit-aws-athena

extra:
  recipe-maintainers:
    - sugatoray
